-- Run this in your Supabase SQL Editor

-- 1. Create Users Table
CREATE TABLE public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    role TEXT NOT NULL CHECK(role IN ('tenant', 'owner', 'admin')),
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Properties Table
CREATE TABLE public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES public.users(id) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT NOT NULL,
    city TEXT NOT NULL,
    address TEXT,
    price REAL NOT NULL,
    price_type TEXT DEFAULT 'month',
    rooms INTEGER DEFAULT 1,
    bathrooms INTEGER DEFAULT 1,
    surface REAL,
    conditions TEXT,
    contact TEXT,
    is_available BOOLEAN DEFAULT true,
    is_sponsored BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'pending',
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Property Images Table
CREATE TABLE public.property_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
    image_path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Favorites Table
CREATE TABLE public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, property_id)
);

-- 5. Create Bookings Table
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES public.properties(id) NOT NULL,
    tenant_id UUID REFERENCES public.users(id) NOT NULL,
    owner_id UUID REFERENCES public.users(id) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_price REAL NOT NULL,
    status TEXT DEFAULT 'pending',
    payment_status TEXT DEFAULT 'unpaid',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Create Reviews Table
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES public.properties(id) NOT NULL,
    tenant_id UUID REFERENCES public.users(id) NOT NULL,
    rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Set up RLS (Row Level Security)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to properties and images
CREATE POLICY "Public properties are viewable by everyone." ON public.properties FOR SELECT USING (status = 'published');
CREATE POLICY "Property images are viewable by everyone." ON public.property_images FOR SELECT USING (true);

-- Allow users to read all other users (for names/contact info)
CREATE POLICY "Users are viewable by everyone" ON public.users FOR SELECT USING (true);

-- Allow a signed-in user to create their own profile if the trigger is delayed
CREATE POLICY "Users can insert own profile." ON public.users FOR INSERT WITH CHECK (auth.uid() = id);

-- Allow users to update their own profile
CREATE POLICY "Users can update own profile." ON public.users FOR UPDATE USING (auth.uid() = id);

-- Helper used by admin RLS policies
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid()
      AND role = 'admin'
      AND status = 'active'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP POLICY IF EXISTS "Admins can manage users." ON public.users;
CREATE POLICY "Admins can manage users." ON public.users
FOR ALL USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Allow owners to manage their own properties and images
DROP POLICY IF EXISTS "Owners can view own properties." ON public.properties;
DROP POLICY IF EXISTS "Owners can insert own properties." ON public.properties;
DROP POLICY IF EXISTS "Owners can update own properties." ON public.properties;
CREATE POLICY "Owners can view own properties." ON public.properties
FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners can insert own properties." ON public.properties
FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners can update own properties." ON public.properties
FOR UPDATE USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Admins can manage properties." ON public.properties;
CREATE POLICY "Admins can manage properties." ON public.properties
FOR ALL USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE POLICY "Owners can insert images for own properties." ON public.property_images
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.properties
    WHERE properties.id = property_images.property_id
    AND properties.owner_id = auth.uid()
  )
);

CREATE POLICY "Owners can delete images for own properties." ON public.property_images
FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM public.properties
    WHERE properties.id = property_images.property_id
    AND properties.owner_id = auth.uid()
  )
);

-- Allow tenants and owners to manage bookings
DROP POLICY IF EXISTS "Tenants can create own bookings." ON public.bookings;
DROP POLICY IF EXISTS "Tenants can view own bookings." ON public.bookings;
DROP POLICY IF EXISTS "Tenants can update payment on own bookings." ON public.bookings;
DROP POLICY IF EXISTS "Owners can view property bookings." ON public.bookings;
DROP POLICY IF EXISTS "Owners can update property bookings." ON public.bookings;

CREATE POLICY "Tenants can create own bookings." ON public.bookings
FOR INSERT WITH CHECK (auth.uid() = tenant_id);

CREATE POLICY "Tenants can view own bookings." ON public.bookings
FOR SELECT USING (auth.uid() = tenant_id);

CREATE POLICY "Tenants can update payment on own bookings." ON public.bookings
FOR UPDATE USING (auth.uid() = tenant_id)
WITH CHECK (auth.uid() = tenant_id);

CREATE POLICY "Owners can view property bookings." ON public.bookings
FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "Owners can update property bookings." ON public.bookings
FOR UPDATE USING (auth.uid() = owner_id)
WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Admins can manage bookings." ON public.bookings;
CREATE POLICY "Admins can manage bookings." ON public.bookings
FOR ALL USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Trigger to insert user into public.users after auth.users signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, full_name, email, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email, COALESCE(new.raw_user_meta_data->>'role', 'tenant'));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. RPC: Increment property views atomically (avoids race conditions and reduces network calls)
CREATE OR REPLACE FUNCTION public.increment_views(row_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.properties
  SET views = views + 1
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
